<?php
    $apiKey = "rzp_test_wbOHIdV06WF1pu";
    $amt=$_POST['amount']*100;
?>
<script src="https://code.jquery.com/jquery-3.5.0.js"></script>
<form action="success.php" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $amt; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'.rand(10,100).'END';?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name=" ECOSPLASH"
    data-description="Where Every Car Gets the Royal Treatment!"
    data-image="https://i.pinimg.com/564x/c6/17/5f/c6175f71ce64784880b38934a2967ab4.jpg"
    data-prefill.firstname="<?php echo $_POST['firstname'];?>"
    data-prefill.phone number="<?php echo $_POST['phoneno'];?>"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form> 
<style>.razorpay-payment-button{display:none;}
</style>
<script type="text/javascript">
$(document).ready(function(){
$('.razorpay-payment-button').click();
}); 
</script>